// Teams actions
export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAMS_FAILED = "GET_TEAMS_FAILED";
export const GET_TEAMS_LOADING = "GET_TEAMS_LOADING";

// Players actions
export const GET_PLAYERS = "GET_PLAYERS";
export const GET_PLAYERS_FAILED = "GET_PLAYERS_FAILED";
export const GET_PLAYERS_LOADING = "GET_PLAYERS_LOADING";
export const SEARCH_PLAYER = "SEARCH_PLAYER";
export const SEARCH_PLAYER_FAILED = "SEARCH_PLAYER_FAILED";
export const SEARCH_PLAYER_LOADING = "SEARCH_PLAYER_LOADING";

// Games actions
export const GET_GAMES = "GET_GAMES";
export const GET_GAMES_FAILED = "GET_GAMES_FAILED";
export const GET_GAMES_LOADING = "GET_GAMES_LOADING";
